### ISSUE TITLE
Improve status  of resources in AssetGroup

### ISSUE THREAD

**Issue by derberg** [kyma-project/rafter#11]
@derberg commented on [Tue Jun 18 2019](https://github.com/kyma-project/kyma/issues/4579)

**Description**

- Status of the ClusterAssetGroup and AssetGroup should change whenever the resource is updated and underlying Asset cr is processed again
- Check if the same is not the case with Asset resources

**Reasons**

At the moment status of resources is not properly updated. If you for example remove one source, or do some other changes and at the end you know that Asset resource is processed, the status should switch to Pending and then again to Ready or Failed.

**Comment by michal-hudy** [comment]
I think it is OK now, so if any change is still needed, please reopen this issue.
