### ISSUE TITLE
Improve README.md files for Rafter components

### ISSUE THREAD

**Issue by kazydek** [kyma-project/rafter#14]
**Description**

This issue is a follow-up of [issue 9](https://github.com/kyma-project/rafter/pull/9) for adding `README.md` files to Rafter components under the `cmd` folder.

The following need to be verified and added in these `README.md` files:

- Tables with environment variables - some of them can be outdated
- The section in each README.md on how to verify your code when developing a given component - this depends on the testing approach we accept for Rafter - whether we decide to test given make targets or test the whole Rafter each time.
- Remove the [testing section](https://github.com/kyma-project/rafter/tree/master/cmd/manager#development) from the controller manager doc as this part is generic and should be included in the development guide

**Issue(s)**
Follow-up of #9

**Comment by derberg** [comment]
- provide short dev guide in docs folder and link to it from Readme files. Explain how to run project for development and run tests, unit and integration
- and move project structure also to docs folder too
