### ISSUE TITLE
Create a Helm Chart for Rafter

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/rafter#2]
**Description**

Create a Helm Chart that will work without Kyma, but can be reused in Kyma.

AC:
 - All exposed values are described in chart Readme
 - Leader election is enabled when controller deployment has more than one instance
 - Globals from Kyma are not used
 - Chart should also install CRD by default, but there should be a way to disable it with a value like install_crd true or something like that

 - Once above points are done and accepted - Have it in Helm Repo (create PR). We know we depend on helm people to approve it, but still, we need to do it. 

**Reasons**

Improve Rafter adoption in Kubernetes users.

**Related issue(s)**
kyma-project/kyma#5585

**Comment by derberg** [comment]
lgtm, only question is what is the plan now to have the chart in helm charts repo?
