### ISSUE TITLE
Add support for Buckets in AssetGroup

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/rafter#4]
**Description**

AssetGroup is not only a new name for DocsTopic, but it also provided a new functionality - the possibility to provide Bucket reference for created Assets. Labels should be also improved.

More details: https://github.com/kyma-project/kyma/issues/5585#issuecomment-540800997

**Reasons**

Give a more control on buckets when working with AssetGroup

**Related issue(s)**
kyma-project/kyma#5585

**Comment by derberg** [comment]
I tried few scanarios, and works like a charm, well done!
sorry for late review :(
