### ISSUE TITLE
Remove leftover mentions of `asset-store` and `cms` from source code

### ISSUE THREAD

**Issue by aerfio** [kyma-project/rafter#47]
**Description**

After migration from Asset Store and hCMS we left some mentions of asset-store in source code, due to the fact that we had to hurry and `it just worked`. This has to be updated.

**Reasons**

Improvements in source code and quality of Rafter as a project

**Comment by aerfio** [comment]
Probably still valid

**Comment by michal-hudy** [comment]
Please do that continuously during work on other tasks
