### ISSUE TITLE
Execute first Rafter release

### ISSUE THREAD

**Issue by derberg** [kyma-project/rafter#50]
**Description**

- Tag repo with `v0.1.0` - **important**
- Create a release in GitHub with changelog
- specify what docker images are considered to be part of 0.1.0
- Make sure docs point to rafter and not asset store any more
- Push release helm chart to our gcs bucket with current chart
- specify in a release that what is blocking us from 1.0 release is lack of support for private buckets and not standard contract on extraction webhook
- Document release process

**Reasons**

it is a mature project that is already used in production for over 6months so it is time to release it officially

**Comment by kwiatekus** [comment]
We dont want to invest in rafter within Kyma organisation. 
The rafter use case is no longer valid for kyma runtime
