### ISSUE TITLE
Add support for removing uploaded content in Rafter Upload Service

### ISSUE THREAD

**Issue by mszostok** [kyma-project/rafter#56]
**Description**

Currently, the [Asset Upload Service](https://kyma-project.io/docs/components/asset-store/#details-asset-upload-service) gives nice functionality for uploading content to Minio.

We need to have also an option to remove that uploaded content. For example, it could be done manually by making `DELETE` call on resource endpoint or automatically garbage collected if none of ClusterDocsTopics/DocTopics are using that.

**AC**
- there is an option to **remove** content uploaded via Asset Upload Service

**Comment by michal-hudy** [comment]
We will rather remove upload service in favor of https://github.com/kyma-project/rafter/issues/66, then you will be able to create your own bucket together with a chart and communicate with storage via S3 API using Bucket CR name.
