### ISSUE TITLE
Official testing pipeline and instruction for switching Rafter Minio into Gateway mode that uses AWS S3

### ISSUE THREAD

**Issue by derberg** [kyma-project/rafter#57]
**Description**

- Get instruction on how to writch Rafter to use AWS S3 through Minio Gateway mode
- Have a testing pipeline that always tests any changes to asset store against gateway mode with AWS S3

**Reasons**

We expect users to use Rafter with Minio Gateway. Minio supports many providers but we should always make sure they are supported within Asset Store and then we need to officially mention it in documentation

**Comment by michal-hudy** [comment]
Not a priority at the moment.
