### ISSUE TITLE
Private buckets support in Rafter

### ISSUE THREAD

**Issue by derberg** [kyma-project/rafter#58]
**Description**

- Support private storage in Asset Store
- Support private storage in Asset Store Upload Service
- Support private storage in Headless CMS:
  - have default private bucket for hcms
  - mark on docstopic and clusterdocstopic info that it is `private`
- Provide proper documentation/tutorials/diagrams
- upload service - validate proposal against current upload service functionality that returns external url to uploaded asset. We need to decide which way to choose, external or internal and if it will even work with private buckets

**Reasons**

There are use cases when you want to use the Asset Store to store files privately. You should be able to store files in a bucket and allow to read it only if the reader is authorized. Some kind of proxy is needed

**Comment by kwiatekus** [comment]
This feature will not be worked on by kyma contributors as we don't see value in this anymore.
We no longer want to host (public or private) assets in the kyma runtime and plan to move that feature to central control plane
