### ISSUE TITLE
Update MinIO dependencies and images

### ISSUE THREAD

**Issue by aerfio** [kyma-project/rafter#69]
**Description**

It's become very hard to update MinIO images as the dependencies are very old (minio/mc image is almost a year old), and the minio subchart is very old too (we have v2.5, newest is v5.0.15!!!). Minio-go is out of date also, but in this case I've tried updating it and no breaking changes were encountered.

The charts here and in Kyma repo are also old.

**Reasons**

If we want to develop this project in the future we need to work with most patched version.
Also the reason I've tried to update Minio was security -> minio images use vulnerable images, old `alpine`s etc

**Attachments**

**Comment by aerfio** [comment]
Security issues have been taken care of by patching minio images in https://github.com/kyma-incubator/third-party-images repo. Chart versions are still old.

**Comment by michal-hudy** [comment]
Do we need something from the newest MinIO version?

**Comment by aerfio** [comment]
We do not need newer MinIO features at the moment, and we patch those images ourselves, so there's no security issues right now @michal-hudy. Can be closed, and reopened in case of bigger rewrite or need of an update 👍
