### ISSUE TITLE
Add 'displayName' field to 'Asset' type

### ISSUE THREAD

**Issue by parostatkiem** [kyma-project/rafter#71]
**Description**
Currently, the _Asset_ has no readable and unique name. We need it to distinguish different assets in ServiceCatalog UI (tab titles, to be precise).
Please read https://github.com/kyma-project/console/issues/1617 to deeper understand the problem.

**Reasons**

**Related issue(s)**

Rafter PR: https://github.com/kyma-project/rafter/pull/72
Documentation + Bumpss in Kyma: https://github.com/kyma-project/kyma/pull/7864
Console issue: https://github.com/kyma-project/console/issues/1617

**Comment by kazydek** [comment]
That would require adding and describing the new field in the CRDs definition in these docs as well:
- [Asset CR](https://kyma-project.io/docs/components/rafter/#custom-resource-asset)
- [AssetGroup CR](https://kyma-project.io/docs/components/rafter/#custom-resource-asset-group)
