### ISSUE TITLE
Make tests more stable in gateway mode

### ISSUE THREAD

**Issue by hudymi** [kyma-project/rafter#76]
**Description**

It happened really often that tests for Gateway mode are failing on CI. We should make them more resilient.

Things to consider:
 - retry in gateway mode - communication with GCP/Azure
 - force Kind version

**Expected result**

Tests are stable

**Actual result**

Tests are failing on communication with GCP/Azure

**Steps to reproduce**

Execute tests on PR

**Troubleshooting**

**Comment by michal-hudy** [comment]
Please do that together https://github.com/kyma-project/rafter/issues/50
