### ISSUE TITLE
Error while installing rafter chart

### ISSUE THREAD

**Issue by AronChristopher93** [kyma-project/rafter#78]
![rafter error](https://user-images.githubusercontent.com/35171177/88476999-1b490d00-cf5a-11ea-82c4-4155c1f75661.PNG)

**Comment by pbochynski** [comment]
Please provide more context:
- How did you install the chart? Directly? From CLI? Installer?
- What version?
- What environment?
- What helm version  do you use?
It will help a lot to investigate the issue.

**Comment by pbochynski** [comment]
Closed due to inactivity
