### ISSUE TITLE
What is the future of Rafter?

### ISSUE THREAD

**Issue by hudymi** [kyma-project/rafter#87]
Recently, I noticed that all issues were closed with the message:

> We dont want to invest in rafter within Kyma organisation.
The rafter use case is no longer valid for kyma runtime

For example https://github.com/kyma-project/rafter/issues/50#issuecomment-705543230

What that it means for the Rafter? Is there a plan to move it to a different organization? Or maybe it will be archived?

Since the beginning, Rafter was designed to work as a standalone project that doesn't require Kyma, so maybe it is no longer valid for Kyma, but it still can be used by someone in the community.

**Comment by derberg** [comment]
if Rafter will be discontinued repo should be archived, or at least a note should be added to Readme.md on top, as it was done with Open Service Broker for Azure -> https://github.com/Azure/open-service-broker-azure. And they added it not upfront on their own but they were confusing the community that had to ask explicitly for clarification -> https://github.com/Azure/open-service-broker-azure/issues/740

**Comment by kwiatekus** [comment]
We have decided to discontinue development of Rafter. We have do not plan any new features and we will limit maintenance to bare minimum within kyma org.

We want to invite new maintainers. I have created a [PR](https://github.com/kyma-project/rafter/pull/89) adding a note about that to the readme and will also send a note on the slack channel.

Rafter's main task of  hosting static content ( i.e documentation or API specs )  will fully taken over by other services:
 - documentation is available on kyma-project.io page
 - service specs are hosted in compass

It follows the overarching goal to reduce the overall footprint of components of the kyma runtime making it more cost-efficient. 
  
Rafter still remains independent on Kyma. Nothing changed here.
It can serve its purpose to others from the community and can be  installed on k8s clusters - completely independent on kyma. 

@derberg @hudymi if you know of anybody interested in taking the maintenance over, please let us know.

**Comment by kwiatekus** [comment]
The PR was merged. Info about current status of the project is now publicly available in the main [readme](https://github.com/kyma-project/rafter) file.
